### ISSUE TITLE
 회원 인증 관련 이슈

### ISSUE THREAD

**Issue by bo1030** [dohy12/project2_PDA#2]
처음 생각한 방식
1. 단순하게 로그인 하면 서버에서  받아온 정보를 My_info에 저장하고 메인 화면으로 넘김
2. 로그아웃 하면 로그인 화면으로 넘김.
3. 서버와 통신은 My_info(변수이름은 아직 미정인데 내정보 관련 변수임) 에서 gruop_id를 받아서 통신할 생각이었습니다. (로그인 할 때 group_id를 받아 오기 때문에 group_id가 있으면 로그인 되었음을 알수있을것같았음)

하지만 이런식으로 하면 혹시 누가 group_id를 알게 되면 로그인을 안 했음에도 다른 유저 정보에 접근이 가능해질것같습니다.

그래서 아래와 같은 방식으로 하면 어떨지 의견을 남겨주세요.

- 서버에 로그인 요청 -> 서버는 로그인 정보를 확인되면 랜덤한 값(대략 64비트)을 생성해서 메인 DB에 cur_user 테이블(그룹 스키마에 추가해서)에 시간, UID, group_id와 같이 올리고  그 랜덤한 값(KEY라고 합시다.)을 어플에 전송을 함
- 서버에 어떤 기능을 요청할때 서버URL을 /{KEY}/서비스 형식으로 함-> 서버에서는 KEY를 대조하고 시간이 30분 이내라면 서비스 제공하고 시간 갱신, 30분 이상이라면 KEY를 테이블에서 삭제하고 어플에서는 로그아웃시킴 -> 만약 대조해서 성공하면 같이 저장된 group_id와 UID를 통해 서비스 제공.
- 위에 더해서 서버는 일정시간 마다 메인의 cur_user 테이블 관리. 
- 로그아웃 시에는 서버에서 그 KEY를 삭제함. 

필수 사항만 올려서 생략된 부분도 있는데 잘 읽어보고 의견 남겨주세요.

**Comment by dohy12** [comment]
1. 유저가 GID, 유저id, 유저pass를 보냄
2. 시스템은 GID, 유저id, 유저pass로 uid를 받아옴
3. 시스템은 uid로 key테이블 검색
4a) 키가 만료되었을 경우 -> key 생성
4b) 30분 안에 생성된 키가 있을 경우 -> key시간 연장 
으로 보면 되나요?

**Comment by bo1030** [comment]
로그인할 경우
1. 어플에서 서버URL/{GID}/login 주소로 ID와 PW(어플에서 ID를 솔트로 해시함수를 돌려서 암호화 한번 진행했음)를 parameter로 get요청함
2. 서버는 GID, 유저id, 유저pass로 인증 진행(유저 테이블에 저장된 salt로 어플에서 온 PW를 해시 함수를 돌려서 hash 값과 비교)함 
3.성공) 시스템은 key 테이블 검색 
3.실패) 실패
4.이미KEY있음) 갱신후 
4.KEY없음) 생성후 KEY 전송

각 기능에서 기능 요청시
1. 어플이 서버URL/{KEY}/(각 서비스)로 각 서비스를 요청을 함
2. URL에 있는 KEY를 보고 KEY 검색
3.있음) 시간확인
3.없음) 로그인 요청. 어플에서는 로그인 페이지로 돌려보냄
4.30분 이내) 시간 갱신 후 KEY 테이블에 저장된 UID, GID를 바탕으로 서비스 제공
4.30분 이후) 로그인 요청. 어플에서는 로그인 페이지로 돌려보냄

**Comment by chenzijian0** [comment]
제 생각:
1.키의 유효기간은 너무 짧을지도 모릅니다.
 사람들이 밤에 자고 다음날 깨서 앱을 이용하는데 비밀번호를 한 번 더 입력해야 하는 것은 비합리적입니다. 아마도 유효기간은 하루 혹은 그 이상이면 좋을 것 같습니다.

2.현재 사용 중인 사용자와 유효 시간을 MySQL 데이터베이스에 저장하면 좋지 않습니다
Mysql의 데이터는 하드디스크에 저장되며, 데이터베이스를 방문할 때마다 많은 시간을 소비합니다. 그래서 우리는 MySQL 데이터베이스의 읽기를 최소화해야 합니다. 따라서 로그인 검증은 JWT를 사용해면 좋습니다. JWT는 그 자체로 시효성이 있으며 데이터베이스를 읽을 필요 없이 서버에서 연산 검증을 하면 됩니다
단점은 JWT가 한번 생성되면 회수할 수 없어 이미 생성된 KEY를 능동적으로 관리할 수 없다는 점입니다.

3.KEY 갱신
저는 Key가 매번 서비스 후에 갱신 필요는 없다고 생각합니다, 우리 KEY의 유효 시간을 연장하고 App 프로그램이 시작될 때나 휴대폰이 다른 프로그램으로 전환된 후 다시 본 App 프로그램으로 전환될 때 KEY 갱신 하는 것이 좋을 거 같습니다

4.KEY를 Http Header에 넣세요
URL에 KEY를 넣면 모든 서비스 함수에 검증이 필요하며, Http Header에 KEY를 넣면 제가 차단기 하나만 만들어서 모든 요청을 일괄 처리할 수 있기 때문에 제 작업량을 크게 줄일 수 있습니다.

5.다른 해결방법
Redis 데이터베이스를 사용합니다. MySQL과 달리 Redis 데이터베이스는 데이터를 메모리에 저장하므로 방문 속도가 빨라집니다. 또한 Redis는 타이머 기능이 있어서 일정 시간이 지나면 자동으로 데이터를 제거할 겁니다. 우리의 필요에 꼭 맞습니다

**Comment by bo1030** [comment]
1. JWT이든 위의 방식이든 해커가 토큰을 탈취하면 위험해집니다. 그래서 최대한 수명은 짧게 하는게 좋을듯합니다.
2. 내용이 길어서 오늘 회의에서 따로 말해봅시다
